### ISSUE TITLE
License is unclear

### ISSUE THREAD

**Issue by preaction** [mjballard/perl-www-letsencrypt#1]
The `LICENSE` file in the root is GPLv3, and the dist.ini file also says "GPL_3", but the module documentation says "These modules are free software; and can be redistributed/modified under the
same terms as Perl itself", which would mean Artistic-1/GPL-1+ at the user's discretion, which is incompatible with the GPLv3 (the Artistic License allows things the GPL does not, especially GPLv3).

**Comment by mjballard** [comment]
Thanks for bringing this up.  The module should read GPLv3. We'll change this shortly.
